apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhello
  namespace: demo-environment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myhello
  template:
    metadata:
      labels:
        app: myhello
    spec:
      containers:
      - name: myhello
        image: anikaseibezeder/myhello:latest
        ports:
        - containerPort: 8888